### ISSUE TITLE
ToB oberen 10 cm "extra"

### ISSUE THREAD

**Issue by StephanRitz** [mkuenzl/sbt-generator#18]
Wenn durch die Probe "C0" die oberen 10 cm der ToB extra ausgewiesen werden, dann bitte diese 10 cm bei den Dicken auch extra erstellen/ausweisen.

Die Schicht wird unter den "Umwelttechnischen Merkmalen" bereits einzeln aufgeführt, soll aber auch in den "Technischen Merkmalen" einzeln aufgeführt werden.

**Comment by mkuenzl** [comment]
Momentan wird es schon einzeln aufgeführt wenn sich das Material der Schichten unterscheidet. Angenommen du willst, dass es in der Material Reihe der Tech. Merkmale einzeln aufgeführt wird.
Falls die darauffolgenden Materialien die selben Eigenschaften/Bezeichnungen haben, dann wird es zusammengefasst.

**Comment by mkuenzl** [comment]
Momentan wird es schon einzeln aufgeführt wenn sich das Material der Schichten unterscheidet. Angenommen du willst, dass es in der Material Reihe der Tech. Merkmale einzeln aufgeführt wird.
Falls die darauffolgenden Materialien die selben Eigenschaften/Bezeichnungen haben, dann wird es zusammengefasst.

**Comment by mkuenzl** [comment]
Momentan wird es schon einzeln aufgeführt wenn sich das Material der Schichten unterscheidet. Angenommen du willst, dass es in der Material Reihe der Tech. Merkmale einzeln aufgeführt wird.
Falls die darauffolgenden Materialien die selben Eigenschaften/Bezeichnungen haben, dann wird es zusammengefasst.

**Comment by mkuenzl** [comment]
Das kombinieren gleicher aufeinander folgender Schichten wurde wieder entfernt. Alle Schichten in der TOB Berichtstabelle werden nun in der Material Reihe einzeln aufgelistet.
