### ISSUE TITLE
Feld neben Belastungsklasse in den Erkundungsstellen

### ISSUE THREAD

**Issue by StephanRitz** [mkuenzl/sbt-generator#20]
Das Feld direkt links neben der "Belastungsklasse" in den Erkundungsstellen bleibt immer leer (besteht eigtl. nur aus Layout-Gründen). Kann das Feld auch grau hinterlegt werden? Bisher ist das weiß, was evtl. implizieren könnte, dass da ein Wert stehen könnte, der nicht eingetragen wurde.

**Comment by mkuenzl** [comment]
Changed Css class. Die Zelle sollte nun immer grau hinterlegt sein.
