### ISSUE TITLE
Sortierung der bei RuK-Anlage ...

### ISSUE THREAD

**Issue by StephanRitz** [mkuenzl/sbt-generator#21]
Hatten wir schon drüber gesprochen aber Karin gewöhnt sich nicht dran und regt sich über die Sortierung auf :D.

Wie aufwändig ist es die Zeilen nach den A's (also eingeteilten Proben) zu sortieren?

**Comment by mkuenzl** [comment]
Ring und Kugel Template wird nun nach Parameter ID sortiert.
