### ISSUE TITLE
Summe in der Berichttabelle GOB runden

### ISSUE THREAD

**Issue by StephanRitz** [mkuenzl/sbt-generator#22]
Bei der Summe "Pechfreier Querschnitt" und "Pechhaltiger Querschnitt" soll weiterhin die Angabe ",5" stehen bleiben, aber nicht mehr ",0". Angaben mit",0" bitte auf ganze Zahlen runden.

**Comment by mkuenzl** [comment]
added DepthTextFormatting to CrossSectionWithoutPitch and CrossSectionWithPitch tableparts
